Feature header
anhnn2401/baitap3 pull request #10
Opened 2020-05-14 07:50 UTC by anhnn2401

2020-05-14 07:55 UTC, sangtx submitted a review, later dismissed
@anhnn2401 em thử tìm hiểu cái menu responsive của bootstrap và áp dụng thử.
https://getbootstrap.com/docs/4.0/components/navbar/
nâng cao skill lên

2020-05-14 07:55 UTC, txsang commented on src/styles/layout/_header.scss
> +      line-height: 4.2;
Line-height này lớn vậy @anhnn2401

2020-05-14 07:55 UTC, txsang commented on src/styles/layout/_header.scss
> +  opacity: 0.6;
Opacity này làm header nó sẽ bị mờ, em nên dùng background rgba thay vì opacity thế này.

2020-05-14 07:55 UTC, txsang commented on src/styles/layout/_header.scss
> +  content: '';
Không để content ở những class thế này @anhnn2401

2020-05-14 08:54 UTC, anhnn2401 commented on src/styles/layout/_header.scss
> +      line-height: 4.2;
cái này e để vào thấy vừa màn hình nên e để đó a

2020-05-14 08:55 UTC, anhnn2401 commented on src/styles/layout/_header.scss
> +  opacity: 0.6;
dạ. để e sửa lại

2020-05-14 09:18 UTC, anhnn2401 commented on src/styles/layout/_header.scss
> +  content: '';
dạ vâng a. e sửa lại đây a.

2020-05-25 07:31 UTC, sangtx requested changes

2020-05-25 07:31 UTC, txsang commented on src/styles/layout/_purchase.scss
> +/*   .btn {
remove những cái em đã comment lại nhé

2020-05-25 07:31 UTC, txsang commented on src/styles/layout/_purchase.scss
> +      @include breakpoint(767) {
xem lại thụt đầu dòng

2020-05-25 07:49 UTC, sangtx approved these changes

2020-05-25 07:49 UTC, merged